# 生产环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app-sms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Mysql#2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 日志配置
logging:
  file:
    name: easyweb-shiro.log
  level:
    root: DEBUG
    com.egao: DEBUG
    com.baomidou.mybatisplus: DEBUG
